DROP TABLE IF EXISTS payouts CASCADE;
DROP TABLE IF EXISTS claims CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS worker_sessions CASCADE;
DROP TABLE IF EXISTS workers CASCADE;
